# -*- coding: utf-8 -*-
"""Projeto da 2ª Unidade

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WkaE5r4EAHcnZY1tNbk1LGImP8mNpwkM

---
# PROJETO DATASET WINE 🍷

Dataset:. https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data


---

IFPE -  Campus Paulista

Curso Tecnológico em Análise e Desenvolvimento de Sistemas

Disciplina: Mineração de Dados

Relatório do Projeto da 2ª Unidade

Equipe:

*   Audemário Alves monteiro filho
*   Gaston Gouveia
*   Paola do Nascimento Rodrigues
*   Wagner Vidal Xavier da Silva

# **1. Compreensão do Negócio**

##  **a. Objetivo de Negócio**

**1. Identificação de Perfis de Vinho:** Analisar os dados para identificar padrões exclusivos de composição química que caracterizam os vinhos produzidos por cada produtor.  

**2. Otimização da Produção:** Identificar fatores específicos na composição química que estão correlacionados com a qualidade do vinho. Isso pode ajudar os produtores a otimizar seus processos de produção para melhorar a consistência e qualidade do produto final.

**3. Classificação de Produtores:** Desenvolver modelos preditivos para classificar automaticamente os vinhos de acordo com o produtor com base em suas características químicas. Isso pode ser útil para autenticação e certificação.

Obs: Decidimos, neste momento, realizar o **item 3,** que trata da **Classificação de Produtores/Classes**, devido ao tempo disponível para a conclusão do projeto.

## **b. Objetivo de Mineração: Que tarefa de mineração será realizada para atingir o objetivo de Negócio?**

Para atingir o objetivo de negócio de "Classificação de Produtores" com base nas características químicas dos vinhos, uma tarefa de mineração comumente realizada é a Classificação. A **Classificação** é uma técnica de aprendizado de máquina supervisionado, na qual um modelo é treinado para categorizar instâncias em classes ou categorias predefinidas.

Aqui estão os passos geralmente seguidos para realizar a tarefa de Classificação neste contexto:

1. **Preparação dos Dados:** Organize os dados de forma que cada instância represente um vinho e suas características químicas.
Atribua rótulos (classes) aos vinhos com base nos produtores.


2. **Divisão dos Dados:** Separe os dados em conjuntos de treinamento e teste. O conjunto de treinamento é usado para treinar o modelo, enquanto o conjunto de teste é usado para avaliar a precisão do modelo.

3. **Seleção de Características:** Identifique as características relevantes para a classificação dos produtores. Isso pode envolver uma análise exploratória para entender a importância de cada característica.

4. **Escolha do Modelo de Classificação:** Selecione um modelo de classificação adequado.

5. **Treinamento do Modelo:**Utilize o conjunto de treinamento para treinar o modelo, ajustando os parâmetros para otimizar o desempenho.

6. **Avaliação do Modelo**: Avalie o modelo usando o conjunto de teste para medir a precisão da classificação. Métricas como acurácia, precisão, recall e F1-score podem ser utilizadas dependendo das características específicas do problema.

7. **Interpretação dos Resultados:** Analise os resultados para entender como o modelo está classificando os vinhos em relação aos produtores. Isso pode incluir a análise de matrizes de confusão para identificar os erros mais comuns.

## **c. Critérios de Sucesso Mineração:**

Definimos como critério primário de sucesso a obtenção de uma devida classificação entre os produtores de vinhos presentes do dataset, nosso objetivo de negócio, que resulte em  boa acurácia e níveis aceitáveis de erros.  

A acurácia do modelo será a métrica essencial para determinar se este atribui corretamente as classes pré-determinadas aos vinhos e consequentemente se é de boa qualidade.  

Idealmente optaríamos por um benchmarking externo, analisando modelos que utilizam a mesma base de dados e compartilham das mesmas intenções quanto ao critério de sucesso para traçar pontos de referência, porém dada a aparente ausência de exemplos com o mesmo critério de sucesso, a classificação entre os produtores, optaremos por um benckmarking interno, comparando os resultados individuais do critério de sucesso entre os cinco algoritmos utilizados.

# **2.Compreensão dos dados**

1. **Introdução aos Dados:**

A base de dados utilizada é uma base de dados com 178 instâncias diferentes de vinhos, divididas em três grandes classes e mais 13 atributos que representam características químicas dos exemplares e incluem diversas medidas como teor alcoólico, ácido málico, cinzas, alcalinidade das cinzas, magnésio, fenóis totais, flavonoides, fenóis não flavonoides, proantocianidinas, intensidade de cor, matiz e OD280/OD315 de vinhos diluídos.

### Instalação e Importação das ferramentas necessárias
"""

#INSTALANDO OPTIMIZADORES
!pip install tpot
!pip install eli5

#Instalação do Pandas Profiling
!pip install --upgrade scipy

!pip install typing_extensions==4.7.1 --upgrade

!pip install ydata-profiling

# Importando bibliotecas que serão utilizadas para análise e modelagem
from ydata_profiling import ProfileReport

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
pd.options.display.float_format = '{:.3f}'.format
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pickle
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, recall_score, f1_score, confusion_matrix, classification_report, precision_recall_curve
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.svm import SVC, LinearSVC
from sklearn.feature_selection import SelectPercentile
from sklearn.metrics import precision_score, recall_score




# %matplotlib inline

# Carregamento do conjunto de dados no Pandas
df = pd.read_csv('Base de dados - Wine.csv')
df.head(5)

"""## **Dicionário dos dados**

1.   Alcohol: Álcool
2.   Malic acid: Ácido málico
3.   Ash: Cinzas
4.   Alcalinity of ash: Alcalinidade das cinzas
5.   Magnesium: Magnésio
6.   Total phenols: Fenóis totais
7.   Flavanoids: Flavonoides
8.   Nonflavanoid phenols: Fenóis não flavonoides
9.   Proanthocyanins: Proantocianinas
10.  Color intensity: Intensidade da cor
11.  Hue: Matiz
12.  OD280/OD315 of diluted wines: OD280/OD315 de vinhos diluídos
13.  Proline: Prolina

## Tipos de Dados
"""

# Aqui verificamos quais as features obeservadas, os tipos delas(numéricas ou categórica) e se precisam de algum pré-processamento:
# Conforme observado, o dataset não precisará de estratégi para os dados ausentes, já que está todo preenchido e também podemos observar os tipos das variáveis
df.info()

# Renomear colunas
df = df.rename(columns = {'Alcohol' : 'Alcool',	'Malicacid': 'Acido_Malico'	,'Ash': 'Cinzas','Alcalinity_of_ash': 'Alcalinidade_de_cinzas'
,'Magnesium': 'Magnesio'	,'Total_phenols': 'Total_fenois','Flavanoids': 'Flavonoides'	,'Nonflavanoid_phenols':'Fenois_não-flavanoides'
,'Proanthocyanins':'Proantocianinas','Color_intensity':'Cor_intensidade','Hue':'Tonalidade'
,'0D280_0D315_of_diluted_wines':'OD280 / OD315 de vinhos diluídos'	,'Proline':'Prolina','class':'classe'})
df.columns

print('A base de dados tem ', df.shape[0] , 'linhas e ', df.shape[1], 'colunas.')

"""Possuímos no total quatorze variáveis. Três delas, "níveis de magnésio, proline e classe", são representadas de forma qualitativa utilizando distinção por classes numéricas de tipo int64, e outra, "intensidade de cor", representada em um tipo object.  

As demais dez variáveis são de tipo numérico float64. Não possuímos dados faltantes de tipo _null_ ou _NaN_.
"""

df.shape

# Alguns parâmetros estatísticos da base
# Estatística descritiva de todas as colunas do DataFrame
df.describe(include = 'all')

"""A partir da descrição dos dados tomamos nota de algumas características iniciais relacionadas aos seus tipos, tal como se encontram.  

A variável intensidade de cores de tipo object possui 132 valores únicos, com os 46 valores possuíndo no mínimo uma repetição onde o valor mais repetido, 2.6, possui 4 repetições. Das variáveis de tipo float64 ou int64 podemos extrair informações estatisticas como média, moda e desvio padrão. Percebemos desde já que a variável tonalidade possui alto desvio padrão, por exemplo.  

Ademais, como é esperado, todos os valores possuem a mesma quantidade de linhas, tornando possível a utilização dos dados como dataset.

## Análise exploratória de Dados:

Utilização do Pandas Profiling:
"""

profile = ProfileReport(df)
profile

eda_data = df.copy()

"""**Compreendendo as colunas de dados:**

1. **Alcool:**   
Alcool apresenta uma distribuição normal com concentração dos valores próximos a média  
Possui alta correlação com Prolina e Classe, onde valores menores de Alcool tendem a classe 1 e valores menores tendem a classe 3.  
Distribui-se de forma quase uniforme entre as classes, sendo a classe 1 majoritária.   
...  
  
2. **Ácido Málico:**   
Acido Málico apresenta uma distribuição unimodal enviesada a esquerda.  
Possui alta correlação com Tonalidade
...  
  
3. **Cinzas:**  
Cinzas apresenta uma distribuição normal e unimodal
...  
  
4. **Alcanilidade de cinzas:**  
Alcalinidade de cinzas apresenta uma distribuição normal e unimodal.
...   
  
5. **Magnésio:**  
Marnésio apresenta uma disbribuição unimodal enviesada a esquerda.  
Possui alta correlação com Prolina.
...  
   
6. **Total de Fenois:**  
Total de Fenois apresenta uma distribuição unimodal.  
Possui alta correlação com Flavonoides, Proantocianinas, OD280/OD315 e Classe
...  
   
7. **Flavanoides:**  
Flavonoides apresenta uma distribuição bimodal enviesada a esquerda.
Possui alta correlação negativa com Fenois não Flavanoides e correlação positiva com OD280/OD315, Total de Fenois, Tonalidade e Classe
...  
  
8. **Fenois não Flavanoides:**  
Fenois não flavanoides apresenta uma distribuição unimodal levemente enviesada a esquerda.  
Possui alta correlação negativa com Flavanoides, OD280/OD315, Total de Fenois e Classe.
...  
  
9. **Proantocianinas:**  
Proantocianinas apresenta uma distribuição unimodal enviesada a esquerda.  
Possui alta correlação com Flavonoides, OD280/OD315 e Total de Fenois.
...  
  
10. **Cor Intensidade:**   
Cor Intensidade apresenta uma distribuição bimodal.
...  
  
11. **Tonalidade:**  
Tonalidade apresenta uma distribuição bimodal levemente enviesada a direita.  
Possui uma alta correlação com ácido malico e flavanoides.
...
  
12. **OD280/OD315:**  
OD280/OD315 apresenta uma distribuição bimodal levemente enviesada a direita.  
Possui alta correlação com flavanoides, proantocianinas, total de fenois e classe.
...
  
13. **Prolina:**  
Prolina apresenta uma distribuição unimodal enviesada a esquerda.  
Possui alta correlação com álcool, magnésio e classe.
...
  
14. **Classe:**  
A distribuição de classes segue uma distribuição normal, com a classe 2 sendo predominante.

Podemos concluir dessa análise que existe uma forte relação entre a quantidade de fenóis em um vinho e sua classificação.. //continuar//
"""

#Gerando os histogramas
plt.figure(figsize= (25,15))
for i, column in enumerate(eda_data.columns):
  plt.subplot(4, 6, i +1)
  sns.histplot(data=eda_data[column])
  plt.title(column)
plt.tight_layout()
plt.show()

"""Correlação de dados"""

# Exibir correlações
df.corr()

# Mapa de calor - exibição das correlações
corr = df.corr()
fig, ax = plt.subplots(figsize=(12, 12))
sns.heatmap(corr, annot=True, cmap="BuPu")

grouped=df.groupby(by='classe').mean()
grouped

"""Abaixo esboçamos gráficos e com eles observamos a distribuição de variáveis em relação as classes quanto a seus valores:
Verificamos qual classe contem os valores mais altos e/ou baixos de cada variável, podendo cruzar essa relação com a diferença/correlação entre variáveis, váriancia e desvio padrão de cada variável. Dito isso, algumas observações que chamam atenção, a exemplo de:

1. Os valores acima de 2.0~ de ácido málico pertendem a _classe 3_  
2. Em flavonoides os valores pertencentes a _classe 3_ não passam de 1.0
3. Em tonalidade há um grande desbalanceamento nas classes, com tons acima de 1~ pertencentes a _classe 2_ exclusivamente.
4. Em prolina todos os valores acima de 700 pertencem a _classe 1_

"""

sns.set()
for index,i in enumerate(grouped.columns,start=1):
    plt.figure(figsize=(6,4))
    sns.barplot(data=grouped,x=grouped.index,y=grouped[i])
    plt.show()

# transformador dtypes cor_intensidade em valores categoricos
df['Cor_intensidade'] = df['Cor_intensidade'].astype('category').cat.codes

#Gerando os histogramas
plt.figure(figsize= (25,15))
for i, column in enumerate(eda_data.columns):
  plt.subplot(4, 6, i +1)
  sns.histplot(data=eda_data[column])
  plt.title(column)
plt.tight_layout()
plt.show()

df.describe()

# Calcular a matriz de correlação
df.corr()

corr = df.corr()
corr.style.background_gradient(cmap='RdBu', axis=None)

#criar um conjunto de gráficos de dispersão para todas as combinações de variáveis no DataFrame
sns.pairplot(df)

df.describe().T

group_soma = df.groupby('classe')
group_soma.sum()

"""# **3. Preparação dos Dados**

Durante a fase de preparação dos dados fez-se necessário a conversão dos valores de *cor intensidade* para tipos numéricos que possam ser compreendidos e utilizados pelos algoritmos assim como no processo consistênte de análise de dados.

Como investigado anteriormente, não foram encontrados valores ausentes de qualquer tipo e ainda que existam distibuições não-gausseanas e enviesadas tampouco ocorreu a necessidade de normalização.  

Quanto os valores fora de escopo, ou outliers, da forma que foram encontrados, foram considerados como ocorrências naturais e não como erros. Devido a baixa ocorrência acreditamos que não haverão impactos negativos significativos ao modelo.
"""

#visualização rápida da presença de outliers
for column in df:
    plt.figure()
    df.boxplot([column])

"""# **4. Modelagem**

Dado que temos um problema de classificação, escolhemos as seguintes abordagens que atendem a este propósito:

##1. Random Forest

Técnica que costuma apresentar boa acurácia em problemas de classificação, permite avaliar o impacto das variáveis independentes, é explicável e de fácil compreensão. Por ser uma abordagem que funciona a partir da avaliação e seleção de vários classificadores, tem um custo computacional maior que técnicas mais simples, no entanto, justamente por se utilizar de várias classificações costuma ser mais asssertiva.

Os dados foram divididos em conjuntos de treinamento(70%) e teste (30%).
### Treinando o modelo no algoritmo de RandomForest
"""



from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Inicialização do Modelo: RandomForestClassifier
modelo = RandomForestClassifier(random_state=2)

# Preparação dos Dados
# X contém todas as características, excluindo a coluna 'classe'.
# y contém apenas a coluna 'classe', que representa as classes a serem previstas.
X = df.drop(['classe'],axis=1)
y = df['classe']

# Divisão dos Dados em Conjuntos de Treinamento e Teste
# X_treino e y_treino são os conjuntos de treinamento (70% dos dados).
# X_teste e y_teste são os conjuntos de teste (30% dos dados).
# O uso de stratify=y garante que a distribuição das classes seja mantida nos conjuntos de treinamento e teste.
X_treino,X_teste, y_treino, y_teste = train_test_split(X,y, test_size=0.3, random_state=42, stratify=y)

y_teste.shape

# Treinamento do Modelo
modelo.fit(X_treino,y_treino)

# Avaliação do Modelo
acuracia = modelo.score(X_teste, y_teste)

# A acurácia é uma métrica comum para avaliar o desempenho do modelo. Pode ser interpretada como a porcentagem de previsões corretas em relação ao total.
# Quanto mais próxima de 1.0, melhor é o desempenho do modelo.
print(f'Acurácia do Modelo: {acuracia}')

sns.boxplot(X_treino, x=y_treino, y='Alcool')

"""Na relação de alcool e classes verificamos que os níveis  mais altos de alcool estão presentes na _classe 1_ e os níveis mais baixos na _classe 2_ onde também observamos a ocorrência de dois possíveis outliers acima de seu limite máximo.  
 Na _classe 3_ se predominam os níveis relativamente mais equilibrados de alcool. os dados contidos no intervalo intermodal parecem distintos quanto a seu nível de álcool.

Observando a distribuição e a distinção das classes quanto ao nível de alcool, podemos considerar os níveis de alcool como um bom indicador para categorizar as classes.
"""

sns.violinplot(X_treino, x=y_treino, y='Alcool')

"""No gráfico violino em todas as classes temos uma distribuição que podemos considerar unimodal. Observamos melhor onde se concentram a maior parte dos valores e adquirimos uma noção melhor sobre a relação de níveis de alcool e a categorização por classe.   

Verificamos que, mesmo que a região do segundo quartil, que concentra a maior parte dos valores daquela classe, seja distinta entra as demais (quanto ao seu nível de álcool) temos uma presença significativa de valores entre duas ou mais classes apresentando os mesmos níveis de alcool, sinificando que, embora seja um bom indicador, o nível de alcool seria capaz de determinar com boa acurácia a classe dos vinhos.
"""

sns.boxplot(X_treino, x=y_treino, y='Flavonoides')

"""Verificamos a distribuição e relação da classe aos níveis de Flavonoides no vinho, similar ao que fizemos com os níveis de álcool.  

Tal como nos níveis de álcool os limites intermodais também mostram a presença de uma distinção de classes para o nível de Flavonoides. Observando os limites superiores e inferiores observamos que os vinhos com maior valor de Flavonoides tendem a ser da _classe 1_ e os menores da _classe 2_
"""

correlacao = pd.concat([X_treino,y_treino],axis=1).corr()
correlacao.style.background_gradient(cmap='RdBu', axis=None)

modelo = RandomForestClassifier(random_state=2)
modelo.fit(X_treino,y_treino)
print(f'Score: {modelo.score(X_teste,y_teste)}')
importancia = pd.DataFrame({'colunas':X_treino.columns,'importancia':modelo.feature_importances_})

importancia_10 = importancia.sort_values(by="importancia", ascending=False).head(10)
plt.figure(figsize=(10,6))
ax = sns.barplot(x='colunas',y='importancia',data=importancia_10)
ax.set_xticklabels(ax.get_xticklabels(), rotation=75);

"""Por fim visualizamos o grau de importância das variáveis para a classificação. Evidenciamos que Alcool e Flavonoides possuem alta relevância para a determinação das classes, algo que pode ser verificado anteriormente.  

Verificamos, por exemplo, que Total de Fenois possui uma importância relativamente baixa para a classificação, mesmo que possua alto grau de correlação com Flavonoides que tem alto grau de importância e alto grau de correlação negativa com classe, nosso Target.

Usando o grau de importância podemos identificar quais variáveis são realmente significativas para a classificação, podendo assim ter uma visão mais compreensiva dos dados e se necessário realizar seleção de atributos.  
Por meio do que foi descrito e dos dados que conhecemos, concluímos que os níveis de alcool, prolina, flavonoides e OD280/OD320 são as principais variáveis necessárias para classificar vinhos entre as três classes de vinhos existentes.

### Usando o KFold

A validação do modelo de classificação a partir da separação dos dados em conjunto de treino e validação faz com que o resultado seja muito dependente dessa divisão dos dados e pode ser que, de forma aleatória, o padrão dos dados de validação sejam diferentes do padrão dos dados de treinamento, levando a sorte de ter um resultado muito melhor do que a realidade ou o azar de um resultado muito pior do que a realidade.

Levando isso em consideração, é possível utilizar a validação cruzada, uma estratégia mais consistente e bem mais utilizada nos projetos de machine learning.

Na validação cruzada, ao invés de separarmos os dados em apenas treino e validação uma única vez, dividimos os dados em várias partes de mesmo tamanho. Em cada uma dessas divisões, será utilizada uma parte para validação e todas as outras para treinamento e o processo se repete até que todas as partes sejam utilizadas para validação e o restante para treinamento.

Será gerado um modelo para cada uma dessas divisões e a avaliação de desempenho será feita tirando a média da métrica de cada modelo. Isso faz com que a dependência da separação dos dados seja eliminada, já que há uma variação maior da escolha dos dados e é retirada uma média.

Geralmente são utilizadas 5 ou 10 partes, mais do que isso não é tão necessário porque necessita de um processamento maior e valores menores já mitiga o problema da escolha dos dados.
"""

# Validação Cruzada

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# Separando os dados em folds
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

previsores = df.iloc[:,0:13].values

previsores

previsores.shape

alvo = df.iloc[:,13].values

alvo.shape

## **Análise das escalas dos atributos (Escalonamento)**
df.describe()

# Utilizará a padronização

from sklearn.preprocessing import StandardScaler

previsores_esc = StandardScaler().fit_transform(previsores)

previsoresdf = pd.DataFrame(previsores_esc)
previsoresdf

previsoresdf.describe()

# Criando o modelo
modelo_Random = RandomForestClassifier(criterion='entropy', random_state = 0, max_depth=3)
resultado_Random = cross_val_score(modelo_Random, previsores_esc, alvo, cv = kfold)

# Usamos a média e o desvio padrão
print("Acurácia Média: %.2f%%" % (resultado_Random .mean() * 100.0))

"""## 2. Árvore de decisão

Decidimos utilizar também o algoritmo de árvore de decisão, que é a base da técnica anterior. Por ser um pouco mais simples, tem um custo computacional menor, o que justifica sua escolha caso os resultados obtidos sejam satisfatórios.
O parâmetro "criterion" foi definido como "entropy" na tentativa de aumentar o ganho de informação à medida em que os nós se aprofundam, reduzindo a aleatoriedade do nó seguinte. Os conjuntos de treino e teste mantiveram a mesma proporção, 70% e 30%, respectivamente.


## Treinando o modelo no algoritmo de Árvore de Decisão
"""

# ARVORE DE DECISÃO

from sklearn.tree import DecisionTreeClassifier

arvore = DecisionTreeClassifier(criterion='entropy', random_state = 0, max_depth=3)
arvore.fit(X_treino, y_treino)

previsoes_arvore = arvore.predict(X_teste)
previsoes_arvore

y_teste

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_arvore) * 100.0))

confusion_matrix(y_teste, previsoes_arvore)

print(classification_report(y_teste, previsoes_arvore))

#**Análise dados de treino**
previsoes_treino = arvore.predict(X_treino)
previsoes_treino

accuracy_score(y_treino, previsoes_treino)

confusion_matrix(y_treino, previsoes_treino)

# Validação Cruzada

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# Separando os dados em folds
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

previsores = df.iloc[:,0:13].values

previsores

previsores.shape

alvo = df.iloc[:,13].values

alvo

alvo.shape

## **Análise das escalas dos atributos (Escalonamento)**
df.describe()

# Utilizará a padronização

from sklearn.preprocessing import StandardScaler

previsores_esc = StandardScaler().fit_transform(previsores)

previsoresdf = pd.DataFrame(previsores_esc)
previsoresdf

previsoresdf.describe()

# Criando o modelo
modelo = DecisionTreeClassifier(criterion='entropy', random_state = 0, max_depth=3)
resultado = cross_val_score(modelo, previsores_esc, alvo, cv = kfold)

# Usamos a média e o desvio padrão
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

"""## 3. KNN
O KNN é um algoritmo simples que não exige um treinamento explícito, sendo baseado no princípio da proximidade entre pontos de dados. Essa abordagem torna-o adaptável a relações não lineares nos dados, capturando padrões complexos de maneira eficaz. O KNN demonstra robustez em relação a outliers, (que, como visto anteriormente, foram mantidos) pois as previsões são influenciadas por uma vizinhança local, minimizando o impacto de pontos isolados.  
 Sua facilidade de atualização também se destaca, permitindo a inclusão de novos dados sem a necessidade de re-treinamento completo, sendo portanto um bom modelo para eventualidades futuras, como adição de novos dados.
### Treinando o modelo no algoritmo de KNN
"""

# **APRENDIZAGEM BASEADA EM INSTÂNCIAS (KNN)**

from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=7, metric='minkowski', p=1)
knn.fit(X_treino, y_treino)

previsoes_knn = knn.predict(X_teste)
previsoes_knn

y_teste

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_knn) * 100.0))

confusion_matrix(y_teste, previsoes_knn)

print(classification_report(y_teste, previsoes_knn))

previsoes_treino = knn.predict(X_treino)
previsoes_treino

accuracy_score(y_treino, previsoes_treino)

confusion_matrix(y_treino, previsoes_treino)

# VALIDAÇÃO CRUZADA

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# Separando os dados em folds
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

# Criando o modelo
modelo = KNeighborsClassifier(n_neighbors=7, metric='minkowski', p = 1)
resultado = cross_val_score(modelo, previsores_esc, alvo, cv = kfold)

# Usamos a média e o desvio padrão
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

"""## 4. Regressão Logística
Escolhemos a regressão loística por sua principal vantagem, a capacidade de modelar relações lineares entre os recursos considerando a probabilidade de pertencer a uma classe específica. Isso facilita a interpretação dos coeficientes associados a cada variável, proporcionando insights sobre a contribuição relativa de cada característica para a decisão de classificação.

Além disso, a regressão logística lida bem com dados multiclasse.

### Treinando o modelo no algoritmo de Regressão Logística




"""

# **REGRESSÃO** LOGÍSTICA

from sklearn.linear_model import LogisticRegression

logistica = LogisticRegression(random_state=1, max_iter=600, penalty="l2",
                               tol=0.0001, C=1,solver="lbfgs")
logistica.fit(X_treino, y_treino)

logistica.intercept_

logistica.coef_

previsoes_logistica = logistica.predict(X_teste)
previsoes_logistica

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_logistica) * 100.0))

confusion_matrix(y_teste, previsoes_logistica)

print(classification_report(y_teste, previsoes_logistica))

# ANÁLISE DE DADOS DE TREINO
previsoes_treino = logistica.predict(X_treino)
previsoes_treino

accuracy_score(y_treino, previsoes_treino)

confusion_matrix(y_treino, previsoes_treino)

# VALIDAÇÃO CRUZADA
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# Separando os dados em folds
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

# Criando o modelo
modelo = LogisticRegression(random_state=1, max_iter=600, penalty="l2",
                               tol=0.0001, C=1,solver="lbfgs")
resultado = cross_val_score(modelo, previsores_esc, alvo, cv = kfold)

# Usamos a média e o desvio padrão
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

"""## 5. SVM

Uma das principais vantagens das SVM é sua eficácia em lidar com conjuntos de dados complexos. Ao buscar a melhor separação entre classes, as SVM buscam otimizar a margem entre os exemplos de treinamento, proporcionando uma generalização robusta para novos dados.
### Treinando o modelo no algoritmo de SVM
"""

# SVM (Support Vector Machine)

from sklearn.svm import SVC

svm = SVC(kernel='rbf', random_state=1, C = 2)
svm.fit(X_treino, y_treino)

previsoes_svm = svm.predict(X_teste)
previsoes_svm

y_teste

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_svm) * 100.0))

confusion_matrix(y_teste, previsoes_svm)

print(classification_report(y_teste, previsoes_svm))

# Análise dados de treino
previsoes_treino = svm.predict(X_treino)
previsoes_treino

accuracy_score(y_treino, previsoes_treino)

confusion_matrix(y_treino, previsoes_treino)

# VALIDAÇÃO CRUZADA

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# Separando os dados em folds
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

# Criando o modelo
modelo = SVC(kernel='rbf', random_state=1, C = 2)
resultado = cross_val_score(modelo, previsores_esc, alvo, cv = kfold)

# Usamos a média e o desvio padrão
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

"""*Rodando* novamente o modelo com tamanho diferente"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

random_forest = RandomForestClassifier()
decision_tree = DecisionTreeClassifier()
knn = KNeighborsClassifier()
logistic_regression = LogisticRegression()
svm_model = SVC()


random_forest.fit(X_train, y_train)
decision_tree.fit(X_train, y_train)
knn.fit(X_train, y_train)
logistic_regression.fit(X_train, y_train)
svm_model.fit(X_train, y_train)

# Faça previsões nos dados de teste
rf_predictions = random_forest.predict(X_test)
dt_predictions = decision_tree.predict(X_test)
knn_predictions = knn.predict(X_test)
lr_predictions = logistic_regression.predict(X_test)
svm_predictions = svm_model.predict(X_test)

# Calcule as métricas de avaliação
rf_accuracy = accuracy_score(y_test, rf_predictions)
rf_f1 = f1_score(y_test, rf_predictions,pos_label='positive',average='micro')
rf_precision = precision_score(y_test, rf_predictions,pos_label='positive',average='micro')
rf_recall = recall_score(y_test, rf_predictions,pos_label='positive',average='micro')

dt_accuracy = accuracy_score(y_test, dt_predictions)
dt_f1 = f1_score(y_test, dt_predictions, pos_label='positive', average='micro')
dt_precision = precision_score(y_test, dt_predictions,pos_label='positive', average='micro')
dt_recall = recall_score(y_test, dt_predictions,pos_label='positive',average='micro')

knn_accuracy = accuracy_score(y_test, knn_predictions)
knn_f1 = f1_score(y_test, knn_predictions, pos_label='positive',average='micro')
knn_precision = precision_score(y_test, knn_predictions,pos_label='positive',average='micro')
knn_recall = recall_score(y_test, knn_predictions,pos_label='positive',average='micro')

lr_accuracy = accuracy_score(y_test, lr_predictions)
lr_f1 = f1_score(y_test, lr_predictions,pos_label='positive',average='micro')
lr_precision = precision_score(y_test, lr_predictions,pos_label='positive',average='micro')
lr_recall = recall_score(y_test, lr_predictions,pos_label='positive',average='micro')

svm_accuracy = accuracy_score(y_test, svm_predictions)
svm_f1 = f1_score(y_test, svm_predictions,pos_label='positive',average='micro')
svm_precision = precision_score(y_test, svm_predictions,pos_label='positive',average='micro')
svm_recall = recall_score(y_test, svm_predictions,pos_label='positive',average='micro')

# Crie a tabela com os resultados

data = {
    'Modelo': ['Random Forest', 'Árvore de Decisão', 'KNN', 'Regressão Logística', 'SVM'],
    'Acurácia': [rf_accuracy, dt_accuracy, knn_accuracy, lr_accuracy, svm_accuracy],
    'F1': [rf_f1, dt_f1, knn_f1, lr_f1, svm_f1],
    'Precisão': [rf_precision, dt_precision, knn_precision, lr_precision, svm_precision],
    'Recall': [rf_recall, dt_recall, knn_recall, lr_recall, svm_recall]
}

df = pd.DataFrame(data)
print(df)

from sklearn.model_selection import KFold, cross_val_score

# Defina o número de folds
num_folds = 30  # Pode ajustar conforme necessário

# Lista de modelos
models = [
    RandomForestClassifier(),
    DecisionTreeClassifier(),
    KNeighborsClassifier(),
    LogisticRegression(),
    SVC()
]

# Lista de nomes dos modelos
model_names = ['Random Forest', 'Árvore de Decisão', 'KNN', 'Regressão Logística', 'SVM']

# Lista para armazenar os resultados
results = {'Modelo': [], 'Acurácia': [], 'F1': [], 'Precisão': [], 'Recall': []}

# Loop através dos modelos
for model, name in zip(models, model_names):
    kfold = KFold(n_splits=num_folds, shuffle=True, random_state=42)

    # Realize a validação cruzada e obtenha as métricas para cada fold
    accuracy = cross_val_score(model, X_train, y_train, cv=kfold, scoring='accuracy').mean()
    f1 = cross_val_score(model, X_train, y_train, cv=kfold, scoring='f1_micro').mean()
    precision = cross_val_score(model, X_train, y_train, cv=kfold, scoring='precision_micro').mean()
    recall = cross_val_score(model, X_train, y_train, cv=kfold, scoring='recall_micro').mean()

    # Armazene os resultados na lista
    results['Modelo'].append(name)
    results['Acurácia'].append(accuracy)
    results['F1'].append(f1)
    results['Precisão'].append(precision)
    results['Recall'].append(recall)

# Crie o DataFrame com os resultados
df_results = pd.DataFrame(results)
print('--------- VALIDAÇÃO CRUZADA --------------------')
print(df_results)

"""---
# Otimização bayesiana para otimizar os hiperparâmetros.

---

A otimização bayesiana é um método para encontrar os melhores hiperparâmetros para um modelo de aprendizado de máquina. Ela se baseia em modelos probabilísticos para modelar a função objetivo (a métrica que você está tentando otimizar) e, com base nisso, escolhe as próximas configurações de hiperparâmetros a serem avaliadas.
"""

pip install scikit-optimize

from skopt import BayesSearchCV
from sklearn.model_selection import StratifiedKFold

# Defina os espaços de busca para os hiperparâmetros de cada modelo
param_spaces = {
    'Random Forest': {
        'n_estimators': (10, 100),
        'max_depth': (1, 20),
        'min_samples_split': (2, 20),
        'min_samples_leaf': (1, 10)
    },
    'Árvore de Decisão': {
        'max_depth': (1, 20),
        'min_samples_split': (2, 20),
        'min_samples_leaf': (1, 10)
    },
    'KNN': {
        'n_neighbors': (1, 20),
        'weights': ['uniform', 'distance']
    },
    'Regressão Logística': {
        'C': (1e-6, 1e+6),
        'penalty': ['l1', 'l2'],
        'solver': ['liblinear']
    },
    'SVM': {
        'C': (1e-6, 1e+6),
        'kernel': ['linear', 'rbf', 'poly'],
        'degree': (1, 3),
    }
}

# Função para otimização bayesiana usando validação cruzada
def bayesian_optimization(model_name, model, param_space, X_train, y_train):
    opt = BayesSearchCV(model, param_space, n_iter=50, n_jobs=-1, cv=StratifiedKFold(n_splits=5), scoring='accuracy')
    opt.fit(X_train, y_train)

    print(f"Melhores hiperparâmetros para {model_name}: {opt.best_params_}")
    return opt.best_estimator_

# Dicionário para armazenar os melhores modelos
best_models = {}

# Loop através dos modelos
for model, name in zip(models, model_names):
    best_model = bayesian_optimization(name, model, param_spaces[name], X_train, y_train)
    best_models[name] = best_model

# Avalie os melhores modelos nos dados de teste
results = {'Modelo': [], 'Acurácia': [], 'F1': [], 'Precisão': [], 'Recall': []}

for name, model in best_models.items():
    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)
    f1 = f1_score(y_test, predictions, pos_label='positive', average='micro')
    precision = precision_score(y_test, predictions, pos_label='positive', average='micro')
    recall = recall_score(y_test, predictions, pos_label='positive', average='micro')

    results['Modelo'].append(name)
    results['Acurácia'].append(accuracy)
    results['F1'].append(f1)
    results['Precisão'].append(precision)
    results['Recall'].append(recall)

# Crie o DataFrame com os resultados
df_results = pd.DataFrame(results)
print(df_results)

"""A otimização bayesiana é usada em conjunto com a validação cruzada para encontrar configurações otimizadas que generalizam bem para diferentes conjuntos de dados.

# **5. Avaliação**

Os algoritmos foram avaliados com base em suas acurácias, precisão, recall e F1-score, onde a Regressão Logística emerge como a melhor alternativa:

##Acurácia
A acurácia é tida comumente como principal métrica de avaliação e nos fornece a taxa de acertos do modelo, a seguir listamos as acuácias de cada modelo:

_Usando o Algoritmo de RandomForest obtivemos uma acurácia de 96% para a primeira iteração_  
_Usando o Algoritmo de KNN obtivemos uma acurácia de 87% para a primeira iteração_  
_Usando o Algoritimo Árvore de decisão obtivemos uma acurácia de 93% para a primeira iteração_  
_Usando o Algoritmo de Regressão Logística obtivemos uma acurácia de 98% para a primeira iteração_  
_Usando o Algoritmo de SMV ovtivemos uma acurácia de 96% para a primeira iteração_  

O algoritmo de Regressão Logística obteve a mais alta acurácia, atingindo **98%** na primeira iteração, atingindo também o maior grau de acurácia na segunda iteração. A acurácia representa a proporção de previsões corretas em relação ao total de previsões. No entanto, a acurácia por si só pode ser enganadora, especialmente em conjuntos de dados desbalanceados.

##Precisão
A precisão é a proporção de verdadeiros positivos em relação ao total de predições positivas. A Regressão Logística apresentou a mais alta precisão em ambas as iterações, indicando que, quando prevê uma classe positiva, é mais provável que esteja correta. Isso é crucial em situações em que falsos positivos são indesejados.

##Recall
O recall representa a proporção de verdadeiros positivos em relação ao total de instâncias positivas no conjunto de dados. Mais uma vez, a Regressão Logística obteve o melhor desempenho em recall em ambas as iterações, indicando que consegue identificar uma alta proporção de exemplos positivos.

##F1-Score
O F1-score é a média harmônica entre precisão e recall. Fornece uma medida balanceada entre essas duas métricas. A Regressão Logística também apresentou o maior F1-score em ambas as iterações, o que reforça sua capacidade de equilibrar precisão e recall de maneira eficaz.

##Finalmente...
Em Conclusão, Algoritmo de Regressão Logística obteve não somente a maior acurácia como também a mais alta precisão, _recall_ e _f1 score_, provando assim ser o melhor modelo para essa base de dados, dado o que queríamos determinar.

-----

Em síntese, ao analisar métricas como Acurácia, Precisão, Recall e F1-Score, destaca-se que a **Regressão Logística** emerge como a opção mais apropriada para resolver este problema de classificação. Isso se deve ao seu notável desempenho e maior habilidade em explicar variações nos dados. Contudo, é crucial ponderar outros aspectos, como a complexidade do modelo, o tempo de treinamento e a interpretabilidade, no processo de escolha do modelo definitivo para uma dada problemática.

## Agradecimento pelo aprendizado , Prof. Flávio!!!! ✅::::: :
"""